//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: Game.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate GameClient, then call methods of this protocol to make API calls.
public protocol GameClientProtocol {
  func connectTo(_ request: ConnectionRequest, callOptions: CallOptions?) -> UnaryCall<ConnectionRequest, ConnectionResult>
  func sendMessage(_ request: ChatMessage, callOptions: CallOptions?) -> UnaryCall<ChatMessage, ChatMessage>
}

public final class GameClient: GRPCClient, GameClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the Game service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Unary call to ConnectTo
  ///
  /// - Parameters:
  ///   - request: Request to send to ConnectTo.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func connectTo(_ request: ConnectionRequest, callOptions: CallOptions? = nil) -> UnaryCall<ConnectionRequest, ConnectionResult> {
    return self.makeUnaryCall(path: "/Game/ConnectTo",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Unary call to SendMessage
  ///
  /// - Parameters:
  ///   - request: Request to send to SendMessage.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func sendMessage(_ request: ChatMessage, callOptions: CallOptions? = nil) -> UnaryCall<ChatMessage, ChatMessage> {
    return self.makeUnaryCall(path: "/Game/SendMessage",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol GameProvider: CallHandlerProvider {
  func connectTo(request: ConnectionRequest, context: StatusOnlyCallContext) -> EventLoopFuture<ConnectionResult>
  func sendMessage(request: ChatMessage, context: StatusOnlyCallContext) -> EventLoopFuture<ChatMessage>
}

extension GameProvider {
  public var serviceName: String { return "Game" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "ConnectTo":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.connectTo(request: request, context: context)
        }
      }

    case "SendMessage":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.sendMessage(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}


// Provides conformance to `GRPCPayload`
extension ConnectionRequest: GRPCProtobufPayload {}
extension ConnectionResult: GRPCProtobufPayload {}
extension ChatMessage: GRPCProtobufPayload {}
